run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 15

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  godot:
    scope: declarations
    exclude:
      - "^fixme:"
      - "^todo:"

  gomnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
      - '10'
      - '100'
      - '1000'

  gosec:
    excludes:
      - G404 # Use of weak random number generator

  lll:
    line-length: 120

  misspell:
    locale: US

  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

  revive:
    rules:
      - name: exported
        disabled: true
      - name: var-naming
        disabled: true

  varnamelen:
    min-name-length: 2
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - id
      - ok
      - db
      - tx
      - ctx
      - wg
      - mu

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - dupl
        - lll
        - goconst
        - goerr113
        - testpackage
        - paralleltest
        - tparallel
        - wrapcheck
        - varnamelen
        - maintidx
        - cyclop
        - gochecknoglobals
        - gochecknoinits
        - exhaustive
        - forbidigo
        - forcetypeassert
        - interfacebloat
        - ireturn
        - nilnil
        - nonamedreturns
        - noctx
        - contextcheck
        - containedctx
        - depguard
        - gomoddirectives
        - gomodguard
        - loggercheck
        - nestif
        - prealloc
        - reassign
        - tenv
        - testableexamples
        - thelper
        - usestdlibvars
        - wsl
        - nlreturn
        - grouper
        - decorder
        - tagaliatelle
        - bidichk
        - durationcheck
        - errchkjson
        - errname
        - errorlint
        - execinquery
        - exportloopref
        - gosec
        - importas
        - makezero
        - nilerr
        - nosprintfhostport
        - promlinter
        - rowserrcheck
        - sqlclosecheck
        - unconvert
        - unparam
        - wastedassign
        - whitespace

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0