run:
  timeout: 5m

linters-settings:
  mnd:
    # Allow numbers in tests
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign

linters:
  enable:
    - errcheck
    - nlreturn
    - mnd
    - govet
    - staticcheck
    - ineffassign
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - nlreturn