version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - nlreturn
    - mnd
    - govet
    - staticcheck
    - ineffassign
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - nlreturn