apiVersion: apps/v1
kind: Deployment
metadata:
  name: matey-mcp-server
  namespace: default
  labels:
    app: matey-mcp-server
    component: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matey-mcp-server
  template:
    metadata:
      labels:
        app: matey-mcp-server
        component: mcp-server
    spec:
      serviceAccountName: matey-mcp-server
      containers:
      - name: matey-mcp-server
        image: mcp.robotrad.io/matey:latest
        imagePullPolicy: Always
        command: ["./matey"]
        args: ["mcp-server", "--port", "8081", "--matey-binary", "/root/matey", "--verbose"]
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: matey-mcp-server
  namespace: default
  labels:
    app: matey-mcp-server
    # CRITICAL: These labels are required for MCP discovery
    mcp.matey.ai/role: server
    mcp.matey.ai/protocol: http
    mcp.matey.ai/server-name: matey
    mcp.matey.ai/capabilities: tools.resources
spec:
  selector:
    app: matey-mcp-server
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP