apiVersion: mcp.matey.ai/v1
kind: MCPServer
metadata:
  name: matey
  namespace: default
  labels:
    app: matey
    component: mcp-server
    mcp.matey.ai/role: server
    mcp.matey.ai/server-name: matey
spec:
  # Container configuration
  image: mcp.robotrad.io/matey:latest
  command: ["./matey"]
  args: ["mcp-server", "--port", "8081"]
  env:
    NAMESPACE: default
  
  # MCP-specific configuration
  protocol: http
  httpPort: 8081
  httpPath: /
  capabilities:
    - tools
    - resources
  
  # Resource requirements
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  # Deployment configuration
  replicas: 1
  serviceAccount: matey-mcp-server
  
  # Service configuration
  serviceType: ClusterIP
  serviceAnnotations:
    mcp.matey.ai/capabilities: "tools.resources"
    mcp.matey.ai/protocol: "http"
    mcp.matey.ai/role: "server"
    mcp.matey.ai/server-name: "matey"
  
  # Service discovery configuration
  serviceDiscovery:
    enabled: true
    discoveryLabels:
      mcp.matey.ai/capabilities: "tools.resources"
      mcp.matey.ai/protocol: "http"
      mcp.matey.ai/role: "server"
      mcp.matey.ai/server-name: "matey"