apiVersion: apps/v1
kind: Deployment
metadata:
  name: matey-proxy
  namespace: default
  labels:
    app: matey-proxy
    component: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matey-proxy
  template:
    metadata:
      labels:
        app: matey-proxy
        component: proxy
    spec:
      serviceAccountName: matey-controller
      containers:
      - name: proxy
        image: mcp.robotrad.io/matey:latest
        imagePullPolicy: Always
        command: ["./matey"]
        args: ["serve-proxy", "--port", "9876", "--namespace", "default", "--api-key", "myapikey"]
        ports:
        - containerPort: 9876
          name: http
        env:
        - name: MCP_API_KEY
          value: myapikey
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9876
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 9876
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: matey-proxy
  namespace: default
  labels:
    app: matey-proxy
    component: proxy
spec:
  selector:
    app: matey-proxy
  ports:
  - name: http
    port: 9876
    targetPort: 9876
    protocol: TCP
  type: NodePort