apiVersion: v2
name: matey
description: A Helm chart for Matey - Kubernetes-native MCP server orchestrator
type: application
version: 0.1.0
appVersion: "0.0.4"

keywords:
  - mcp
  - model-context-protocol
  - kubernetes
  - orchestrator
  - ai

maintainers:
  - name: Phil Dougherty
    email: phil@example.com

home: https://github.com/phildougherty/m8e
sources:
  - https://github.com/phildougherty/m8e

dependencies:
  - name: registry
    version: "2.8.3"
    repository: "https://charts.helm.sh/stable"
    condition: registry.enabled
    optional: true