apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-scheduler
  namespace: default
  labels:
    app.kubernetes.io/name: task-scheduler
    app.kubernetes.io/component: task-scheduler
    app.kubernetes.io/managed-by: matey
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: task-scheduler
  labels:
    app.kubernetes.io/name: task-scheduler
    app.kubernetes.io/component: task-scheduler
    app.kubernetes.io/managed-by: matey
rules:
# Core Kubernetes resources for job management
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# MCP Custom Resources
- apiGroups: ["mcp.matey.ai"]
  resources: ["mcptaskschedulers", "mcptaskschedulers/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["mcp.matey.ai"]
  resources: ["mcpservers", "mcpmemory", "mcpproxies"]
  verbs: ["get", "list", "watch"]
# Events for logging and debugging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: task-scheduler
  labels:
    app.kubernetes.io/name: task-scheduler
    app.kubernetes.io/component: task-scheduler
    app.kubernetes.io/managed-by: matey
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: task-scheduler
subjects:
- kind: ServiceAccount
  name: task-scheduler
  namespace: default