{{- if .Values.proxy.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matey.fullname" . }}-auth
  labels:
    {{- include "matey.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.proxy.auth.apiKey | default (randAlphaNum 32) | b64enc | quote }}
{{- end }}

---
{{- if and .Values.registry.enabled (not .Values.registry.builtin.enabled) .Values.registry.username .Values.registry.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matey.fullname" . }}-registry-auth
  labels:
    {{- include "matey.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.registry.endpoint .Values.registry.username .Values.registry.password (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc }}
{{- end }}