apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflows.mcp.matey.ai
  labels:
    app.kubernetes.io/name: matey
    app.kubernetes.io/component: workflow-crd
spec:
  group: mcp.matey.ai
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - schedule
            - steps
            properties:
              schedule:
                type: string
                description: "Cron expression defining when the workflow should run"
                example: "0 */6 * * *"
              timezone:
                type: string
                description: "Timezone for schedule interpretation (defaults to UTC)"
                example: "America/New_York"
              enabled:
                type: boolean
                description: "Whether the workflow is active"
                default: true
              suspend:
                type: boolean
                description: "Prevent new executions while keeping the workflow definition"
                default: false
              steps:
                type: array
                description: "Sequence of actions to execute in the workflow"
                items:
                  type: object
                  required:
                  - name
                  - tool
                  properties:
                    name:
                      type: string
                      description: "Unique identifier for this step within the workflow"
                    tool:
                      type: string
                      description: "MCP tool to execute"
                    parameters:
                      type: object
                      description: "Parameters for the tool execution (supports templating)"
                      additionalProperties: true
                    condition:
                      type: string
                      description: "Condition to determine if this step should execute (supports templating)"
                    timeout:
                      type: string
                      description: "Timeout for this specific step"
                      pattern: '^([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$'
                    retryPolicy:
                      type: object
                      properties:
                        maxRetries:
                          type: integer
                          minimum: 0
                          maximum: 10
                          description: "Maximum number of retry attempts"
                        retryDelay:
                          type: string
                          pattern: '^([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$'
                          description: "Delay between retry attempts"
                        backoffPolicy:
                          type: string
                          enum: ["Linear", "Exponential", "Fixed"]
                          description: "How retry delays are calculated"
                        maxRetryDelay:
                          type: string
                          pattern: '^([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$'
                          description: "Maximum delay between retries"
                    dependsOn:
                      type: array
                      description: "Steps that must complete successfully before this step"
                      items:
                        type: string
                    continueOnError:
                      type: boolean
                      description: "Allow the workflow to continue even if this step fails"
                      default: false
                    runPolicy:
                      type: string
                      enum: ["Always", "OnSuccess", "OnFailure", "OnCondition"]
                      description: "When this step should run"
                      default: "OnSuccess"
              retryPolicy:
                type: object
                description: "Retry behavior for the entire workflow"
                properties:
                  maxRetries:
                    type: integer
                    minimum: 0
                    maximum: 10
                    description: "Maximum number of retry attempts"
                  retryDelay:
                    type: string
                    pattern: '^([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$'
                    description: "Delay between retry attempts"
                  backoffPolicy:
                    type: string
                    enum: ["Linear", "Exponential", "Fixed"]
                    description: "How retry delays are calculated"
                  maxRetryDelay:
                    type: string
                    pattern: '^([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$'
                    description: "Maximum delay between retries"
              timeout:
                type: string
                description: "Timeout for the entire workflow execution"
                pattern: '^([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$'
              concurrencyPolicy:
                type: string
                enum: ["Allow", "Forbid", "Replace"]
                description: "How many workflow executions can run simultaneously"
                default: "Allow"
              successfulJobsHistoryLimit:
                type: integer
                minimum: 0
                maximum: 100
                description: "Number of successful job executions to keep"
                default: 3
              failedJobsHistoryLimit:
                type: integer
                minimum: 0
                maximum: 100
                description: "Number of failed job executions to keep"
                default: 1
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["", "Pending", "Running", "Succeeded", "Failed", "Suspended", "Completed"]
                description: "Current phase of the workflow"
              conditions:
                type: array
                description: "Latest available observations of workflow's current state"
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ["Scheduled", "Executing", "Succeeded", "Failed", "Suspended", "Validated", "Progressing"]
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              lastScheduleTime:
                type: string
                format: date-time
                description: "Last time the workflow was scheduled"
              nextScheduleTime:
                type: string
                format: date-time
                description: "Next time the workflow will be scheduled"
              lastExecutionTime:
                type: string
                format: date-time
                description: "When the most recent execution started"
              lastSuccessTime:
                type: string
                format: date-time
                description: "When the workflow last completed successfully"
              activeJobs:
                type: array
                description: "Currently running jobs for this workflow"
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    uid:
                      type: string
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    startTime:
                      type: string
                      format: date-time
              executionHistory:
                type: array
                description: "Status of recent workflow executions"
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    startTime:
                      type: string
                      format: date-time
                    endTime:
                      type: string
                      format: date-time
                    phase:
                      type: string
                      enum: ["", "Pending", "Running", "Succeeded", "Failed", "Suspended", "Completed"]
                    message:
                      type: string
                    duration:
                      type: string
                    jobReference:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        uid:
                          type: string
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        startTime:
                          type: string
                          format: date-time
                    stepResults:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          phase:
                            type: string
                            enum: ["Pending", "Running", "Succeeded", "Failed", "Skipped", "Retrying"]
                          output:
                            type: object
                          error:
                            type: string
                          duration:
                            type: string
                          attempts:
                            type: integer
              stepStatuses:
                type: object
                description: "Status of each step in the most recent execution"
                additionalProperties:
                  type: object
                  properties:
                    phase:
                      type: string
                      enum: ["Pending", "Running", "Succeeded", "Failed", "Skipped", "Retrying"]
                    startTime:
                      type: string
                      format: date-time
                    endTime:
                      type: string
                      format: date-time
                    message:
                      type: string
                    retryCount:
                      type: integer
                    output:
                      type: object
                    error:
                      type: string
              observedGeneration:
                type: integer
                description: "Most recent generation observed by the controller"
              message:
                type: string
                description: "Additional information about the workflow status"
    additionalPrinterColumns:
    - name: Schedule
      type: string
      jsonPath: .spec.schedule
    - name: Enabled
      type: boolean
      jsonPath: .spec.enabled
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Last Run
      type: date
      jsonPath: .status.lastExecutionTime
    - name: Next Run
      type: date
      jsonPath: .status.nextScheduleTime
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: workflows
    singular: workflow
    kind: Workflow
    shortNames:
    - wf
    - workflows